on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      name: Checking out repository

    - uses: subosito/flutter-action@v2
      name: Installing Flutter
      with:
        flutter-version: '3.10.2'
        channel: 'stable'

    - name: Build Flutter
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          flutter build web --base-href "/" -t "lib/main_production.dart" --release -v
        else
          flutter build web --base-href "/" -t "lib/main_development.dart" --release -v
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .ci/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/givt-app-kids-web:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/givt-app-kids-web:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        id: install

      - name: Log in to K8S Dev
        if: contains(github.ref, 'development')
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DEV_US_KUBECONF }}

      - name: Log in to K8S Prod
        if: contains(github.ref, 'main')
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.PROD_US_KUBECONF }}
      
      - name: Set hostname for kube bake
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "HOSTNAME=www.givt4kids.app" >> $GITHUB_ENV
          else
            echo "HOSTNAME=dev.givt4kids.app" >> $GITHUB_ENV
          fi
 
      - uses: azure/k8s-bake@v2.2
        with:
          renderEngine: "helm"
          helmChart: ".kube-manifests/"
          overrides: | 
            dockerTag:${{ github.sha }}
            hostName:${{ env.HOSTNAME }}
          helm-version: "latest"
        id: bake
        
      - name: Deploy to the Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            givt/givt-app-kids-web:${{ github.sha }}