on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      name: Checking out repository

    - uses: subosito/flutter-action@v2
      name: Installing Flutter
      with:
        flutter-version: '3.10.2'
        channel: 'stable'

    - name: build flutter
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          flutter build web --base-href "/" -t "lib/main_production.dart" --release -v
        else
          flutter build web --base-href "/" -t "lib/main_development.dart" --release -v
        fi
    
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .ci/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/givt-app-kids-web:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/givt-app-kids-web:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max